name: Build
on:
  push:
    # TODO: See if we shouldn't run certain build operations on MRs only
    #       vs running them on forks and branches
    branches:
      - "**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Analyze
        run: go vet ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
      - name: Test
        run: |
          echo $SHELL
          ./test.sh
